name: Swhelper
version: '${project.version}'
main: com.hb.swhelper.SWHelper
api-version: 1.18
depend:
  - Skywars


commands:
  swh:
    description: This is the main plugin command.
    usage: '/swh rkit|resetWin|allEvents|start'