name: Swhelper
version: '${project.version}'
main: com.hb.swhelper.SWHelper
api-version: 1.18
depend:
  - Skywars


commands:
  swh:
    description: This is the main plugin command.
    usage: '/swh rkit <0|1|2|3> 0: disable kit; 1: player can choose kit; 2: each player gets different random kits; 3: each player gets same kit§r'